name: Publish

on:
  release:
    types: [ created ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          registry-url: "https://registry.npmjs.org"

      - name: Create and publish npm package
        run: cd nodejs-client && npm ci && npm run build && npm run promote
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH }}