name: Publish

on:
  workflow_dispatch:
  release:
    types: [ created ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install Node.js dependencies
        working-directory: nodejs-client
        run: npm ci

      - name: Run tests
        working-directory: nodejs-client
        run: npm test

      - name: Run build
        working-directory: nodejs-client
        run: npm run build

      - name: Publish npm package
        working-directory: nodejs-client/dist
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH }}