name: Publish

on:
  workflow_dispatch:
  release:
    types: [ created ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install Node.js dependencies
        working-directory: npm
        run: npm ci

      - name: Run tests
        working-directory: npm
        run: npm test

      - name: Run build
        working-directory: npm
        run: npm run build

      - name: Publish npm package
        working-directory: npm
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH }}